version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
install:
  - git submodule update --init --recursive
  
platform:
  - Any CPU

configuration:
  - Release
  
build:
  project: src/Dependencies.Viewer.sln
  verbosity: minimal