version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
install:
  - git submodule update --init --recursive
  
platform:
  - Any CPU

configuration:
  - Release

before_build:
  - ps: nuget restore src/Dependencies.Viewer.sln


build:
  project: src/Dependencies.Viewer.sln
  verbosity: minimal

artifacts:
  - path: Build\Release
    name: Dependencies Viewer
    type: zip