name: Master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/doc/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.typo-ci.yml'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/doc/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.typo-ci.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Install sonar scanner
      run: dotnet tool install --global dotnet-sonarscanner --version 4.10.0
      working-directory: src
  
    - name: Restore nuget packages
      run: msbuild -t:restore
      working-directory: src

    - name: start sonar scanner
      run: dotnet sonarscanner begin /o:xclemence /k:xclemence_Dependencies.Viewer /d:sonar.host.url=https://sonarcloud.io /d:sonar.exclusions=**/obj/**,**/*.dll
    
    - name: Build sources
      run: msbuild src/Dependencies.Viewer.sln /p:Configuration=Release 
    
    - name: VSTest
      run: vstest.console.exe **/bin/**/Dependencies.Viewer.UnitTests.dll /Platform:x64 /EnableCodeCoverage
      working-directory: src

    - name: stop sonar scanner
      run: dotnet sonarscanner end 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - uses: actions/upload-artifact@v2
      with:
        name: DependenciesViewer
        path: Build/Release/
